apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: omnimind
  namespace: argocd
spec:
  description: OmniMind application project
  sourceRepos:
    - 'https://github.com/AlexBoyev/OmniMind.git'
  destinations:
    - namespace: 'omnimind-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
