---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: omnimind-staging
spec:
  type: ExternalName
  externalName: staging-postgres.omnimind-staging.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: omnimind-staging
spec:
  type: ExternalName
  externalName: staging-redis.omnimind-staging.svc.cluster.local
